const parseToISODate = require("./parseToISODate");
const getRCInsertQuery = (id, data) => {
  const myqueryrc = `
    INSERT INTO rc_details (
        fk_users,
        reg_no,
        vehicle_class,
        chassis,
        engine,
        vehicle_manufacturer_name,
        model,
        vehicle_colour,
        fuel_type,
        norms_type,
        body_type,
        owner_count,
        owner_name,
        owner_father_name,
        vehicle_status,
        status_as_on,
        reg_authority,
        reg_date,
        vehicle_manufacturing_month_year,
        rc_expiry_date,
        vehicle_tax_upto,
        vehicle_insurance_company_name,
        vehicle_insurance_upto,
        vehicle_insurance_policy_number,
        rc_financer,
        present_address,
        permanent_address,
        vehicle_cubic_capacity,
        vehicle_cylinders_no,
        vehicle_seat_capacity,
        vehicle_standing_capacity,
        wheelbase,
        pucc_number,
        pucc_upto,
        blacklist_status,
        permit_issue_date,
        permit_number,
        permit_type,
        permit_valid_from,
        permit_valid_upto,
        non_use_status,
        non_use_to,
        national_permit_number,
        national_permit_upto,
        national_permit_issued_by,
        is_commercial,
        noc_details,
        rto_code,
        financed,
        raw_response,
        rc_expiry_remaining_datys,
        insurance_expiry_remaining_datys,
        pucc_expiry_remaining_datys
    )
    VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
        $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
        $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
        $31,$32,$33,$34,$35,$36,$37,$38,$39,$40,
        $41,$42,$43,$44,$45,$46,$47,$48,$49,$50,
        -- Remaining days = expiry date - today (NULL when the date is absent).
        -- $20 = rc_expiry_date, $23 = vehicle_insurance_upto, $34 = pucc_upto.
        CASE WHEN $20::date IS NULL THEN NULL ELSE ($20::date - CURRENT_DATE) END,
        CASE WHEN $23::date IS NULL THEN NULL ELSE ($23::date - CURRENT_DATE) END,
        CASE WHEN $34::date IS NULL THEN NULL ELSE ($34::date - CURRENT_DATE) END
    )
    RETURNING
        id,
        reg_no,
        vehicle_manufacturer_name,
        model,
        fuel_type,
        vehicle_colour,
        vehicle_class,
        vehicle_insurance_upto,
        permit_valid_from,
        permit_valid_upto,
        national_permit_upto,
        rc_expiry_date,
        pucc_upto,
        rc_expiry_remaining_datys,
        insurance_expiry_remaining_datys,
        pucc_expiry_remaining_datys;
  `;

  const valuesrc = [
    id,
    data.reg_no,
    data.vehicle_class || null,
    data.chassis || null,
    data.engine || null,
    data.vehicle_manufacturer_name || null,
    data.model || null,
    data.vehicle_colour || null,
    data.fuel_type || null,
    data.norms_type || null,
    data.body_type || null,
    data.owner_count || null,
    data.owner_name || null,
    data.owner_father_name || null,
    data.vehicle_status || null,
    parseToISODate(data.status_as_on),
    data.reg_authority || null,
    parseToISODate(data.reg_date),
    data.vehicle_manufacturing_month_year || null,
    parseToISODate(data.rc_expiry_date),
    parseToISODate(data.vehicle_tax_upto),
    data.vehicle_insurance_company_name || null,
    parseToISODate(data.vehicle_insurance_upto),
    data.vehicle_insurance_policy_number || null,
    data.rc_financer || null,
    data.present_address || null,
    data.permanent_address || null,
    data.vehicle_cubic_capacity || null,
    data.vehicle_cylinders_no || null,
    data.vehicle_seat_capacity || null,
    data.vehicle_standing_capacity || null,
    data.wheelbase || null,
    data.pucc_number || null,
    parseToISODate(data.pucc_upto),
    data.blacklist_status || null,
    parseToISODate(data.permit_issue_date),
    data.permit_number || null,
    data.permit_type || null,
    parseToISODate(data.permit_valid_from),
    parseToISODate(data.permit_valid_upto),
    data.non_use_status || null,
    parseToISODate(data.non_use_to),
    data.national_permit_number || null,
    parseToISODate(data.national_permit_upto),
    data.national_permit_issued_by || null,
    data.is_commercial || null,
    data.noc_details || null,
    data.rto_code || null,
    data.financed || null,
    data.raw_response || null,
  ];

  return {
    myqueryrc,
    valuesrc,
  };
};
module.exports = getRCInsertQuery;
